import { BackgroundEffects, PageHeader } from "../components/background";
import { Navigation } from "../components/navigation";
import { Footer } from "../components/footer";

export default function TermsPage() {
  return (
    <>
      <BackgroundEffects />
      <Navigation />
      
      <PageHeader 
        title="Terms of Service"
        subtitle="Last updated: November 27, 2025"
      />
      
      <section className="py-8 sm:py-12 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <div className="glass-card p-6 sm:p-8 md:p-10 space-y-10">
            
            {/* Acceptance */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-pink mb-4">
                1. Acceptance of Terms
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>
                  By downloading, installing, or using the Aura mobile application (&quot;App&quot;) and related services (collectively, the &quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
                </p>
                <p>
                  These Terms constitute a legally binding agreement between you and Aura. We may modify these Terms at any time, and your continued use of the Service constitutes acceptance of modified Terms.
                </p>
              </div>
            </div>

            {/* Eligibility */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-blue mb-4">
                2. Eligibility
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>To use Aura, you must:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Be at least 13 years old (or the minimum age in your jurisdiction)</li>
                  <li>If under 18, have parental or guardian consent</li>
                  <li>Have the legal capacity to enter into these Terms</li>
                  <li>Not be prohibited from using the Service under applicable laws</li>
                </ul>
                <p>By using the Service, you represent and warrant that you meet these eligibility requirements.</p>
              </div>
            </div>

            {/* Account */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-purple mb-4">
                3. Your Account
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>You are responsible for:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Notifying us immediately of any unauthorized access</li>
                  <li>Ensuring your account information is accurate and current</li>
                </ul>
                <p>We reserve the right to suspend or terminate accounts that violate these Terms or for any other reason at our sole discretion.</p>
              </div>
            </div>

            {/* User Content */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-orange mb-4">
                4. User Content & Photos
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">4.1 Your Photos</strong></p>
                <p>You retain ownership of photos you upload. By uploading photos, you grant Aura a limited, non-exclusive license to process these photos solely for providing the Service to you.</p>
                
                <p><strong className="text-white">4.2 Photo Requirements</strong></p>
                <p>You represent and warrant that:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You own or have rights to all photos you upload</li>
                  <li>Photos are of yourself OR you have explicit written consent from the person depicted</li>
                  <li>Photos do not violate any third party&apos;s rights</li>
                  <li>Photos comply with applicable laws</li>
                </ul>
                
                <p><strong className="text-white">4.3 Generated Content</strong></p>
                <p>Images generated by the Service are AI-created content based on your inputs. You receive a license to use generated images for personal and commercial purposes, subject to these Terms. You acknowledge that generated images are not photographs and may not accurately represent real events or locations.</p>
              </div>
            </div>

            {/* Prohibited Uses */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-coral mb-4">
                5. Prohibited Uses
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>You agree NOT to use the Service to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Create non-consensual imagery:</strong> Generate images of individuals without their explicit consent</li>
                  <li><strong>Produce illegal content:</strong> Create child sexual abuse material, content depicting minors in sexual situations, or any illegal content</li>
                  <li><strong>Generate explicit content:</strong> Create pornographic, sexually explicit, or obscene material</li>
                  <li><strong>Create harmful content:</strong> Generate content depicting violence, gore, torture, or harm to individuals or animals</li>
                  <li><strong>Impersonate others:</strong> Create content falsely representing public figures, celebrities, or other individuals</li>
                  <li><strong>Commit fraud:</strong> Use generated content for fraud, scams, phishing, or deceptive purposes</li>
                  <li><strong>Spread misinformation:</strong> Create fake news, political disinformation, or misleading content</li>
                  <li><strong>Harass or bully:</strong> Create content intended to harass, intimidate, or harm others</li>
                  <li><strong>Violate rights:</strong> Infringe on intellectual property, privacy, or other rights</li>
                  <li><strong>Circumvent safety:</strong> Attempt to bypass our content filters or safety measures</li>
                </ul>
                <p className="text-pop-coral">Violation of these prohibitions may result in immediate account termination, content removal, and potential legal action.</p>
              </div>
            </div>

            {/* Payments */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-lime mb-4">
                6. Payments & Subscriptions
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">6.1 Pricing</strong></p>
                <p>Prices for subscriptions and in-app purchases are displayed in the App. We reserve the right to change prices at any time. Price changes will not affect current subscription periods.</p>
                
                <p><strong className="text-white">6.2 Billing</strong></p>
                <p>All purchases are processed through Apple App Store or Google Play. Payment terms are governed by their respective terms of service.</p>
                
                <p><strong className="text-white">6.3 Subscriptions</strong></p>
                <p>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period. Cancel through your device&apos;s subscription settings.</p>
                
                <p><strong className="text-white">6.4 Refunds</strong></p>
                <p>Refund requests are handled by Apple or Google according to their policies. We do not directly process refunds for app store purchases.</p>
              </div>
            </div>

            {/* AI Disclaimer */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-pink mb-4">
                7. AI-Generated Content Disclaimer
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">7.1 Nature of Generated Content</strong></p>
                <p>All images generated by Aura are created using artificial intelligence. Generated images are NOT photographs and do not depict real events, locations, or situations.</p>
                
                <p><strong className="text-white">7.2 No Accuracy Guarantee</strong></p>
                <p>We do not guarantee the accuracy, quality, or suitability of generated content. Results may vary and are subject to AI limitations.</p>
                
                <p><strong className="text-white">7.3 Digital Watermarking</strong></p>
                <p>Generated images may contain invisible digital watermarks (SynthID or similar technology) identifying them as AI-generated.</p>
                
                <p><strong className="text-white">7.4 User Responsibility</strong></p>
                <p>YOU are solely responsible for how you use, represent, and distribute generated content. Misrepresenting AI-generated images as real photographs may have legal consequences.</p>
              </div>
            </div>

            {/* Intellectual Property */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-blue mb-4">
                8. Intellectual Property
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">8.1 Our Intellectual Property</strong></p>
                <p>The Service, including its design, features, content, and technology, is owned by Aura and protected by copyright, trademark, and other intellectual property laws. &quot;Aura&quot; and our logo are trademarks.</p>
                
                <p><strong className="text-white">8.2 License to Use</strong></p>
                <p>We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service for personal purposes in accordance with these Terms.</p>
                
                <p><strong className="text-white">8.3 Restrictions</strong></p>
                <p>You may not: copy, modify, or distribute our software; reverse engineer or decompile the App; create derivative works; or use our intellectual property without permission.</p>
              </div>
            </div>

            {/* Disclaimer of Warranties */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-purple mb-4">
                9. Disclaimer of Warranties
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p className="uppercase font-semibold">
                  THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR ACCURACY.
                </p>
                <p>We do not warrant that:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The Service will be uninterrupted, secure, or error-free</li>
                  <li>Results will meet your expectations or requirements</li>
                  <li>Generated content will be accurate or suitable for any purpose</li>
                  <li>Defects will be corrected</li>
                </ul>
              </div>
            </div>

            {/* Limitation of Liability */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-orange mb-4">
                10. Limitation of Liability
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p className="uppercase font-semibold">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, AURA AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
                </p>
                <p>
                  OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100, WHICHEVER IS GREATER.
                </p>
                <p>Some jurisdictions do not allow limitation of liability, so these limitations may not apply to you.</p>
              </div>
            </div>

            {/* Indemnification */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-lime mb-4">
                11. Indemnification
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>
                  You agree to indemnify, defend, and hold harmless Aura and its affiliates, officers, directors, employees, and agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising from:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Your use of the Service</li>
                  <li>Your violation of these Terms</li>
                  <li>Your violation of any third party&apos;s rights</li>
                  <li>Content you upload or generate</li>
                  <li>Your negligence or willful misconduct</li>
                </ul>
              </div>
            </div>

            {/* Termination */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-pink mb-4">
                12. Termination
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">12.1 By You</strong></p>
                <p>You may terminate your account at any time through the app settings. Upon termination, your Identity Vault and associated data will be deleted.</p>
                
                <p><strong className="text-white">12.2 By Us</strong></p>
                <p>We may suspend or terminate your account immediately, without prior notice, for any reason including violation of these Terms, suspected fraud, or legal requirements.</p>
                
                <p><strong className="text-white">12.3 Effect of Termination</strong></p>
                <p>Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination (including indemnification, limitation of liability, and dispute resolution) shall survive.</p>
              </div>
            </div>

            {/* Dispute Resolution */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-blue mb-4">
                13. Dispute Resolution
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p><strong className="text-white">13.1 Informal Resolution</strong></p>
                <p>Before filing any formal dispute, you agree to contact us at <a href="mailto:legal@auraapp.com" className="text-pop-pink hover:underline">legal@auraapp.com</a> to attempt informal resolution.</p>
                
                <p><strong className="text-white">13.2 Binding Arbitration</strong></p>
                <p>Any disputes not resolved informally shall be resolved through binding arbitration, rather than in court, except for claims eligible for small claims court.</p>
                
                <p><strong className="text-white">13.3 Class Action Waiver</strong></p>
                <p>YOU AGREE TO RESOLVE DISPUTES INDIVIDUALLY AND WAIVE ANY RIGHT TO PARTICIPATE IN CLASS ACTIONS OR CLASS ARBITRATIONS.</p>
              </div>
            </div>

            {/* Governing Law */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-purple mb-4">
                14. Governing Law
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any legal action must be brought in the courts located in Delaware.</p>
              </div>
            </div>

            {/* General */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-orange mb-4">
                15. General Provisions
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and Aura.</li>
                  <li><strong>Severability:</strong> If any provision is found unenforceable, other provisions remain in effect.</li>
                  <li><strong>Waiver:</strong> Failure to enforce any right does not waive that right.</li>
                  <li><strong>Assignment:</strong> You may not assign these Terms. We may assign our rights freely.</li>
                  <li><strong>Force Majeure:</strong> We are not liable for failures due to circumstances beyond our control.</li>
                </ul>
              </div>
            </div>

            {/* Contact */}
            <div>
              <h2 className="text-xl sm:text-2xl font-bold font-[family-name:var(--font-syne)] text-pop-lime mb-4">
                16. Contact Information
              </h2>
              <div className="space-y-4 text-white/70 font-[family-name:var(--font-jakarta)] text-sm sm:text-base leading-relaxed">
                <p>For questions about these Terms, contact us at:</p>
                <ul className="list-none space-y-2">
                  <li><strong>Legal:</strong> <a href="mailto:legal@auraapp.com" className="text-pop-pink hover:underline">legal@auraapp.com</a></li>
                  <li><strong>Support:</strong> <a href="mailto:support@auraapp.com" className="text-pop-pink hover:underline">support@auraapp.com</a></li>
                </ul>
              </div>
            </div>
            
          </div>
        </div>
      </section>
      
      <Footer />
    </>
  );
}
